<?php
declare(strict_types=1);

namespace AlexNo\FieldLingoGii\AddLanguageColumn\Adapter\Migration;

use Yii;
use yii\gii\CodeFile;

/**
 * Represents migration PHP file generated by MigrationAdapter.
 */
final class MigrationCodeFile extends CodeFile
{
    public string $className;

    public function __construct(string $fileName, string $content, string $className)
    {
        $this->className = $className;

        // CRITICAL: resolve alias BEFORE calling parent constructor
        // Base CodeFile uses $this->path for:
        // 1. Computing $this->id = md5($this->path)
        // 2. Checking file existence via is_file($this->path)
        // 3. Determining operation (CREATE/OVERWRITE/SKIP)
        $migrationsPath = Yii::getAlias('@app/migrations');
        $fullPath = $migrationsPath . DIRECTORY_SEPARATOR . $fileName;

        // Parent will correctly set all properties based on real path
        parent::__construct($fullPath, $content);

        // Do NOT override operation - parent already set it correctly
    }

    public function preview(): string
    {
        $escaped = htmlspecialchars($this->content, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
        return <<<HTML
<pre><code class="php hljs">{$escaped}</code></pre>
<script type="text/javascript">
if (typeof hljs !== 'undefined') {
    hljs.highlightAll();
}
</script>
HTML;
    }

    public function getContent(): string
    {
        return $this->content;
    }

    public function getFileName(): string
    {
        return basename($this->path);
    }

    public function getRelativePath(): string
    {
        // We show a beautiful name in UI Gii
        return "migrations/{$this->className}.php";
    }
}
