<?php
declare(strict_types=1);
namespace AlexNo\FieldLingoGii\AddLanguageColumn\Adapter\Migration;
/**
 * MigrationCodeFile
 * Represents migration PHP file generated by MigrationAdapter.
 *
 * @license https://opensource.org/licenses/MIT MIT
 * @package AlexNo\FieldLingoGii\AddLanguageColumn
 * @author Oleksandr Nosov <alex@4n.com.ua>
 * @copyright 2025 Oleksandr Nosov
 * @subpackage AddLanguageColumn
 */

use Yii;
use yii\gii\CodeFile;

final class MigrationCodeFile extends CodeFile
{
    /**
     * Path to migrations directory (relative to project root).
     * @var string
     */
    private string $migrationPath;

    /**
     * Constructor.
     *
     * CRITICAL: resolve alias BEFORE calling parent constructor
     * Base CodeFile uses $this->path for:
     *   1. Computing $this->id = md5($this->path)
     *   2. Checking file existence via is_file($this->path)
     *   3. Determining operation (CREATE/OVERWRITE/SKIP)
     *
     * Do NOT override operation - parent already set it correctly
     *
     * @param string $fileName
     * @param string $content
     * @param string $className
     * @param string|null $migrationPath Optional path to migrations directory.
     *                                    If null or empty — 'migrations' will be used.
     */
    public function __construct(string $fileName, string $content, public string $className, ?string $migrationPath = null)
    {
        // resolve migrations path (path from root of the project to migrations directory)
        $this->migrationPath = $migrationPath ?: 'migrations';

        // Parent expects a path (real or intended) — parent will check file existence using that path
        $fullPath = Yii::getAlias('@app/') . $this->getRelativePath();
        parent::__construct($fullPath, $content);
    }

    /**
     * Returns a preview of the code file with syntax highlighting.
     *
     * @return string HTML content with syntax-highlighted code
     * @see https://highlightjs.org/usage/
     */
    public function preview(): string
    {
        $escaped = htmlspecialchars($this->content, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
        return <<<HTML
<pre><code class="php hljs">{$escaped}</code></pre>
<script type="text/javascript">
if (typeof hljs !== 'undefined') {
    hljs.highlightAll();
}
</script>
HTML;
    }

    /**
     * Returns the content of the code file.
     * @return string the content of the code file
     * @see CodeFile::content
     */
    public function getContent(): string
    {
        return $this->content;
    }

    /**
     * Returns the file name of the code file.
     * @return string the file name of the code file
     * @see CodeFile::path
     */
    public function getFileName(): string
    {
        return basename($this->path);
    }

    /**
     * Returns the relative path of the code file for display purposes.
     * @return string the relative path of the code file
     */
    public function getRelativePath(): string
    {
        // We show a beautiful name in UI Gii
        return "{$this->migrationPath}/{$this->className}.php";
    }

}
