<?php
declare(strict_types=1);

namespace AlexNo\FieldLingoGii\AddLanguageColumn\Adapter\Migration;

use Yii;
use AlexNo\FieldLingoGii\AddLanguageColumn\Adapter\AbstractAdapter;
use yii\db\TableSchema;
use AlexNo\FieldLingoGii\AddLanguageColumn\Adapter\AdapterInterface;

/**
 * MigrationAdapter
 *
 * Generates migration CodeFile(s) that add new language-localized columns.
 */
final class MigrationAdapter extends AbstractAdapter implements AdapterInterface
{
    /**
     * @inheritDoc
     */
    public function generateFor(TableSchema $table, string $baseName, array $columns, string $newLanguageSuffix, array $options = []): array
    {
        $this->options = array_merge($this->options, $options);

        $newColumn = "{$baseName}_{$newLanguageSuffix}";
        $sourceName = $this->resolveSourceColumn($table, $baseName, $columns);
        if ($sourceName === null || !isset($table->columns[$sourceName])) {
            return [];
        }

        // Skip if column already exists (generator will record skipped)
        if (array_key_exists($newColumn, $table->columns)) {
            return [];
        }

        $source = $table->columns[$sourceName];

        // timestamp for filename and class name uniqueness
        $ts = time();
        $className = $this->buildMigrationClassName($table->name, $newColumn, $ts);
        $fileName = "m" . date('ymd_His', $ts) . "_add_{$newColumn}_to_{$table->name}.php";

        $migrationContent = $this->buildMigrationContent($table, $baseName, $columns, $newColumn, $className);

        $file = new MigrationCodeFile($fileName, $migrationContent, $className);

        return [$file];
    }

    private function buildMigrationClassName(string $tableName, string $columnName, int $ts): string
    {
        $safeTable = preg_replace('/[^A-Za-z0-9_]/', '_', $tableName);
        $safeColumn = preg_replace('/[^A-Za-z0-9_]/', '_', $columnName);
        return 'm' . date('ymd_His', $ts) . "_add_{$safeColumn}_to_{$safeTable}";
    }

    /**
     * Build migration content. We generate conservative code: addColumn with generic `$this->string()`
     * and a commented example of how to run ALTER TABLE for MySQL position if needed.
     */
    private function buildMigrationContent(TableSchema $table, string $baseName, array $columns, string $newColumnName, string $className): string
    {
        $sourceName = $this->resolveSourceColumn($table, $baseName, $columns) ?? $columns[0];
        $source = $table->columns[$sourceName];

        $dbTypeHint = $this->normalizeDbTypeForMigration($source->dbType ?? null);
        $allowNull = $source->allowNull ? 'true' : 'false';
        $tableName = $table->name;
        $positionComment = '';

        // MySQL-specific position snippet for user convenience
        if (Yii::$app->db->driverName === 'mysql') {
            $pos = $this->options['position'] ?? 'after_all';
            if ($pos === 'before_all') {
                $allNames = array_keys($table->columns);
                $idx = array_search($columns[0], $allNames, true);
                if ($idx !== false && $idx > 0) {
                    $after = $allNames[$idx - 1];
                    $positionComment = "ALTER TABLE `{$tableName}` MODIFY COLUMN `{$newColumnName}` {$source->dbType} " . ($source->allowNull ? 'NULL' : 'NOT NULL') . " AFTER `{$after}`;";
                } else {
                    $positionComment = "ALTER TABLE `{$tableName}` MODIFY COLUMN `{$newColumnName}` {$source->dbType} " . ($source->allowNull ? 'NULL' : 'NOT NULL') . " FIRST;";
                }
            } else {
                $after = $columns[array_key_last($columns)];
                $positionComment = "ALTER TABLE `{$tableName}` MODIFY COLUMN `{$newColumnName}` {$source->dbType} " . ($source->allowNull ? 'NULL' : 'NOT NULL') . " AFTER `{$after}`;";
            }
        }

        // produce migration class content (conservative, user can edit for exact types/positions)
        $class = <<<PHP
<?php
declare(strict_types=1);

use yii\db\Migration;

/**
 * Class {$className}
 * Auto-generated by Field-Lingo Gii: add column {$newColumnName} to table {$tableName}
 */
final class {$className} extends Migration
{
    public function safeUp(): void
    {
        // Column hint (derived from existing column): {$dbTypeHint}
        // Adjust the expression below if you want an exact migration expression like \$this->string(255)->notNull()
        \$this->addColumn('{$tableName}', '{$newColumnName}', \$this->string());
        // If you need the column to be placed in a specific position (MySQL), you can run the following SQL:
        // {$positionComment}
    }

    public function safeDown(): void
    {
        if (\$this->db->getSchema()->getTableSchema('{$tableName}', true)->getColumn('{$newColumnName}') !== null) {
            \$this->dropColumn('{$tableName}', '{$newColumnName}');
        }
    }
}
PHP;

        return $class;
    }
}
