<?php
declare(strict_types=1);

namespace AlexNo\FieldLingoGii\AddLanguageColumn\Adapter\Migration;

use yii\gii\CodeFile;

/**
 * Represents migration PHP file generated by MigrationAdapter.
 */
final class MigrationCodeFile extends CodeFile
{
    public string $className;

    public function __construct(string $fileName, string $content, string $className)
    {
        parent::__construct('@app/migrations/' . $fileName, $content);

        $this->className = $className;
        $this->operation = parent::OP_CREATE;
    }

    public function preview(): string
    {
        $escaped = htmlspecialchars($this->content, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
        return <<<HTML
<pre><code class="php hljs">{$escaped}</code></pre>
<script type="text/javascript">
if (typeof hljs !== 'undefined') {
    hljs.highlightAll();
}
</script>
HTML;
    }

    public function getContent(): string
    {
        return $this->content;
    }

    public function getFileName(): string
    {
        return basename($this->path);
    }

    public function getRelativePath(): string
    {
        return "Migration — {$this->className}.php";
    }
}
